# Generated by Django 5.1.1 on 2024-09-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100)),
                ('tool_capacity', models.PositiveIntegerField()),
                ('tool_offset', models.FloatField()),
                ('feedrate', models.PositiveIntegerField()),
                ('tool_in_use', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
