# Generated by Django 5.1.1 on 2024-09-10 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_name', models.CharField(choices=[('X', 'X Axis'), ('Y', 'Y Axis'), ('Z', 'Z Axis'), ('A', 'A Axis'), ('C', 'C Axis')], max_length=1)),
                ('max_acceleration', models.PositiveIntegerField()),
                ('max_velocity', models.PositiveIntegerField()),
                ('actual_position', models.FloatField()),
                ('target_position', models.FloatField()),
                ('distance_to_go', models.FloatField()),
                ('homed', models.BooleanField()),
                ('acceleration', models.PositiveIntegerField()),
                ('velocity', models.PositiveIntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
    ]
