# Generated by Django 5.1.1 on 2024-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axis',
            name='distance_to_go',
            field=models.FloatField(editable=False),
        ),
    ]
